alias PitchforkApi.Repo
alias PitchforkApi.Artist
alias PitchforkApi.Album

albums = [
  %{"name": "7/27", "rating": 6.2, "artist": "Fifth Harmony"},
  %{"name": "DJ-Kicks", "rating": 7.7, "artist": "Dâm-Funk"},
  %{"name": "Collapse", "rating": 7.4, "artist": "Seiho"},
  %{"name": "Skin", "rating": 6.4, "artist": "Flume"},
  %{"name": "Modern ", "rating": 8.0, "artist": "William Tyler"},
  %{"name": "Suck on This", "rating": 5.0, "artist": "Die Antwoord"},
  %{"name": "Awkward  Songs", "rating": 7.9, "artist": "Jank"},
  %{"name": "Mark Kozelek Sings Favorites", "rating": 5.5, "artist": "Mark Kozelek"},
  %{"name": "Congrats", "rating": 6.6, "artist": "Holy Fuck"},
  %{"name": "Folding Time", "rating": 6.0, "artist": "Sepalcure"},
  %{"name": "Angry Angles", "rating": 7.6, "artist": "Angry Angles"},
  %{"name": "Murder for Hire 2", "rating": 7.4, "artist": "Kevin Gates"},
  %{"name": "Kidsticks", "rating": 7.6, "artist": "Beth Orton"},
  %{"name": "Minor Victories", "rating": 6.0, "artist": "Minor Victories"},
  %{"name": "Rock the Fuck on Forever", "rating": 6.9, "artist": "Angel Du$t"},
  %{"name": "Mosey", "rating": 7.1, "artist": "Daniel Romano"},
  %{"name": "X-Communicate", "rating": 7.5, "artist": "Kristin Kontrol"},
  %{"name": "The Dream is Over", "rating": 7.8, "artist": "PUP"},
  %{"name": "Tempo", "rating": 7.9, "artist": "Olga Bell"},
  %{"name": "Mondo Alterado", "rating": 7.4, "artist": "Rebolledo"},
  %{"name": "elseq 1", "rating": 7.0, "artist": "Autechre"},
  %{"name": "elseq 2", "rating": 6.6, "artist": "Autechre"},
  %{"name": "elseq 3", "rating": 6.9, "artist": "Autechre"},
  %{"name": "elseq 4", "rating": 7.1, "artist": "Autechre"},
  %{"name": "elseq 5", "rating": 6.8, "artist": "Autechre"},
  %{"name": "The Last Word on First Blues", "rating": 7.9, "artist": "Allen Ginsberg"},
  %{"name": "Ere Gobez", "rating": 8.1, "artist": "Debo Band"},
  %{"name": "EP 4", "rating": 7.0, "artist": "Wolf Parade"},
  %{"name": "Taste", "rating": 7.7, "artist": "Islands"},
  %{"name": "Should I Remain Here at Sea?", "rating": 7.7, "artist": "Islands"},
  %{"name": "Earrings Off!", "rating": 6.0, "artist": "Adult"},
  %{"name": "Dangerous Woman", "rating": 7.6, "artist": "Ariana Grande"},
  %{"name": "Good Luck and Do Your Best", "rating": 7.4, "artist": "Gold Panda"},
  %{"name": "Four Organs / Phase Patterns", "rating": 7.6, "artist": "Steve Reich"},
  %{"name": "Put the Kid on the Sleepy Horse", "rating": 6.5, "artist": "Mock Orange"},
  %{"name": "Changesonebowie", "rating": 8.8, "artist": "David Bowie"},
  %{"name": "Infrared", "rating": 7.7, "artist": "Dawn Richard"},
  %{"name": "Kamikaze", "rating": 7.0, "artist": "So So Glos"},
  %{"name": "Juarez", "rating": 8.0, "artist": "Terry Allen"},
  %{"name": "Fallen Angels", "rating": 6.4, "artist": "Bob Dylan"},
  %{"name": "The Triad", "rating": 8.0, "artist": "Pantha du Prince"},
  %{"name": "Pythagorean Dream", "rating": 7.6, "artist": "Rhys Chatham"},
  %{"name": "Ullages", "rating": 6.6, "artist": "Eagulls"},
  %{"name": "Wave", "rating": 7.5, "artist": "Christian Naujoks"},
  %{"name": "Strangers", "rating": 7.6, "artist": "Marissa Nadler"},
  %{"name": "These People", "rating": 5.1, "artist": "Richard Ashcroft"},
  %{"name": "Beyond the Bloodhounds", "rating": 7.9, "artist": "Adia Victoria"},
  %{"name": "Andando el Tiempo", "rating": 7.8, "artist": "Carla Bley"},
  %{"name": "Teens of Denial", "rating": 8.5, "artist": "Car Seat Headrest"},
  %{"name": "August 26th", "rating": 5.2, "artist": "Post Malone"},
  %{"name": "A New Wave of Violence", "rating": 6.9, "artist": "Head Wound City"},
  %{"name": "In Glendale", "rating": 6.5, "artist": "Tim Heidecker"},
  %{"name": "Day of the Dead", "rating": 8.1, "artist": "Various Artists"},
  %{"name": "Skip a Sinking Stone", "rating": 7.0, "artist": "Mutual Benefit"},
  %{"name": "Union and Return", "rating": 7.3, "artist": "Torn Hawk"},
  %{"name": "Cut and Paste", "rating": 6.5, "artist": "Oscar"},
  %{"name": "Oh No", "rating": 7.9, "artist": "Jessy Lanza"},
  %{"name": "Tired of Tomorrow", "rating": 8.0, "artist": "Nothing"},
  %{"name": "Pile", "rating": 8.2, "artist": "A Giant Dog"},
  %{"name": "What Follows", "rating": 6.7, "artist": "Shit Robot"},
  %{"name": "Coloring Book", "rating": 9.1, "artist": "Chance the Rapper"},
  %{"name": "Full of It ", "rating": 7.2, "artist": "Summer Cannibals"},
  %{"name": "Fool", "rating": 6.9, "artist": "Jameszoo"},
  %{"name": "Happy Songs for Happy Zombies", "rating": 6.9, "artist": "Pinkshinyultrablast"},
  %{"name": "The Complete Prestige 10-Inch LP Collection", "rating": 8.4, "artist": "Miles Davis"},
  %{"name": "Holy Ghost", "rating": 7.7, "artist": "Modern Baseball"},
  %{"name": "Nattesferd", "rating": 8.0, "artist": "Kvelertak"},
  %{"name": "I Hear You", "rating": 6.8, "artist": "Arbor Labor Union"},
  %{"name": "Venus on Edge", "rating": 7.3, "artist": "Hooded Fang"},
  %{"name": "Heartbreaker (Deluxe Reissue)", "rating": 9.0, "artist": "Ryan Adams"},
  %{"name": "Konnichiwa", "rating": 7.8, "artist": "Skepta"},
  %{"name": "The Heart Speaks in Whispers", "rating": 7.6, "artist": "Corinne Bailey Rae"},
  %{"name": "Bloom Forever", "rating": 7.9, "artist": "Thomas Cohen"},
  %{"name": "99.9%", "rating": 8.0, "artist": "Kaytranada"},
  %{"name": "Under the Sun", "rating": 7.6, "artist": "Mark Pritchard"},
  %{"name": "Down in Heaven", "rating": 7.2, "artist": "Twin Peaks"},
  %{"name": "55", "rating": 7.4, "artist": "Bacao Rhythm & Steel Band"},
  %{"name": "Bottomless Pit", "rating": 8.1, "artist": "Death Grips"},
  %{"name": "a 2: The Heart of Noise", "rating": 4.9, "artist": "Jean-Michel Jarre"},
  %{"name": "Get In", "rating": 7.2, "artist": "Pita"},
  %{"name": "Get Gone", "rating": 6.8, "artist": "Seratones"},
  %{"name": "A Moon Shaped Pool", "rating": 9.1, "artist": "Radiohead"},
  %{"name": "Spiritual Songs for Lovers to Sing", "rating": 7.8, "artist": "LUH"},
  %{"name": "Take Me to the Alley", "rating": 6.7, "artist": "Gregory Porter"},
  %{"name": "The Things That We Are Made Of", "rating": 6.8, "artist": "Mary Chapin Carpenter"},
  %{"name": "The Colour in Anything", "rating": 8.2, "artist": "James Blake"},
  %{"name": "Cult Following", "rating": 7.5, "artist": "Little Scream"},
  %{"name": "Kindness for Weakness", "rating": 6.7, "artist": "Homeboy Sandman"},
  %{"name": "For Good", "rating": 7.0, "artist": "Fog"},
  %{"name": "Will", "rating": 8.2, "artist": "Julianna Barwick "},
  %{"name": "Island Universe Story: Selected Works", "rating": 7.8, "artist": "Helado Negro"},
  %{"name": "Piatto D'Oro", "rating": 6.6, "artist": "Meyhem Lauren"},
  %{"name": "As If Apart", "rating": 7.4, "artist": "Chris Cohen"},
  %{"name": "songs from wonder.land", "rating": 5.0, "artist": "Various Artists"},
  %{"name": "Luck or Magic", "rating": 5.0, "artist": "Britta Phillips"},
  %{"name": "Beloved", "rating": 6.0, "artist": "Mo Troper"},
  %{"name": "Paradise", "rating": 8.4, "artist": "White Lung"},
  %{"name": "Another Splash of Colour - New Psychedelia in Britain 1980-1985", "rating": 7.2, "artist": "Various Artists"},
  %{"name": "Terminal Redux", "rating": 8.2, "artist": "Vektor"},
  %{"name": "Trágame Tierra", "rating": 4.7, "artist": "Big Black Delta"},
  %{"name": "HOPELESSNESS", "rating": 9.0, "artist": "ANOHNI"},
  %{"name": "White Hot Moon", "rating": 6.5, "artist": "Pity Sex"},
  %{"name": "Junjo Presents: Wins the World Cup", "rating": 7.7, "artist": "Various Artists"},
  %{"name": "Guided Meditation", "rating": 7.1, "artist": "Hurry"},
  %{"name": "The Impossible Kid", "rating": 8.2, "artist": "Aesop Rock"},
  %{"name": "Egyptian Lover 1983-1988", "rating": 8.0, "artist": "Egyptian Lover"},
  %{"name": "Nonagon Infinity", "rating": 8.0, "artist": "King Gizzard & The Lizard Wizard"},
  %{"name": "Blue Wave", "rating": 7.5, "artist": "Operators"},
  %{"name": "Honey", "rating": 7.0, "artist": "Katy B"},
  %{"name": "Close To the Noise Floor - Formative UK a 1975 - 1984", "rating": 8.1, "artist": "Various Artists"},
  %{"name": "Crime Cutz", "rating": 7.0, "artist": "Holy Ghost!"},
  %{"name": "Testarossa", "rating": 7.2, "artist": "Yoni & Geti"},
  %{"name": "VIEWS", "rating": 6.8, "artist": "Drake"},
  %{"name": "DJ Koze Presents Pampa Vol. 1", "rating": 7.4, "artist": "Various Artists"},
  %{"name": "The Feminine: Act I", "rating": 6.9, "artist": "Anna Wise"},
  %{"name": "Modernists", "rating": 7.6, "artist": "Alarm Will Sound"},
  %{"name": "Sign O' the Times", "rating": 10.0, "artist": "Prince"},
  %{"name": "1999", "rating": 10.0, "artist": "Prince"},
  %{"name": "Parade", "rating": 9.1, "artist": "Prince & The Revolution"},
  %{"name": "Diamonds and Pearls", "rating": 8.3, "artist": "Prince & The New Power Generation"},
  %{"name": "Purple Rain", "rating": 10.0, "artist": "Prince & The Revolution"},
  %{"name": "Dirty Mind", "rating": 10.0, "artist": "Prince"},
  %{"name": "Controversy", "rating": 9.0, "artist": "Prince"},
  %{"name": "Around the World in a Day", "rating": 8.8, "artist": "PrinceThe Revolution"},
  %{"name": "Nocturnal Koreans", "rating": 7.0, "artist": "Wire"},
  %{"name": "All Jokes Aside", "rating": 7.5, "artist": "Dej Loaf"},
  %{"name": "Asphalt for Eden", "rating": 7.8, "artist": "Dälek"},
  %{"name": "Interventions", "rating": 7.9, "artist": "Horse Lords"},
  %{"name": "The Ship", "rating": 8.0, "artist": "Brian Eno"},
  %{"name": "Triangle", "rating": 6.4, "artist": "Susanna"},
  %{"name": "The Stone Junction", "rating": 7.1, "artist": "Audio Push"},
  %{"name": "Lemonade", "rating": 8.5, "artist": "Beyoncé"},
  %{"name": "Always Strive and Prosper", "rating": 7.3, "artist": "A$AP Ferg"},
  %{"name": "New Misery", "rating": 6.2, "artist": "Cullen Omori"},
  %{"name": "Double Ecstasy EP", "rating": 6.9, "artist": "Antwon"},
  %{"name": "Too Many Voices", "rating": 7.1, "artist": "Andy Stott"},
  %{"name": "At Last!", "rating": 9.0, "artist": "Etta James"},
  %{"name": "Bergtatt", "rating": 8.7, "artist": "Ulver"},
  %{"name": "Kveldssanger", "rating": 7.0, "artist": "Ulver"},
  %{"name": "Nattens Madrigal", "rating": 8.2, "artist": "Ulver"},
  %{"name": "Dolls of Highland", "rating": 8.1, "artist": "Kyle Craft"},
  %{"name": "Delusions of Grand Fur", "rating": 5.7, "artist": "Rogue Wave"},
  %{"name": "Lost Themes II", "rating": 5.6, "artist": "John Carpenter"},
  %{"name": "Some Other Time: the Lost Session from the Black Forest ", "rating": 8.4, "artist": "Bill Evans"},
  %{"name": "Rosecrans", "rating": 6.8, "artist": "DJ QuikProblem"},
  %{"name": "Waltzed in from the Rumbling", "rating": 6.8, "artist": "Plants and Animals"},
  %{"name": "Blood Visions", "rating": 9.1, "artist": "Jay Reatard"},
  %{"name": "Konono N°1 Meets Batida", "rating": 6.8, "artist": "Konono N°1Batida"},
  %{"name": "The Future of Death", "rating": 8.0, "artist": "Primitive Weapons"},
  %{"name": "It Kindly Stopped for Me", "rating": 6.6, "artist": "Sorority Noise"},
  %{"name": "Please Be Honest", "rating": 5.9, "artist": "Guided By Voices"},
  %{"name": "Tower of Meaning", "rating": 7.0, "artist": "Arthur Russell"},
  %{"name": "Phases", "rating": 7.0, "artist": "Cellars"},
  %{"name": "Yoyogi Park", "rating": 7.9, "artist": "Lawrence"},
  %{"name": "The Diary", "rating": 6.9, "artist": "J Dilla"},
  %{"name": "Music of Morocco: Recorded by Paul Bowles 1959", "rating": 8.9, "artist": "Various Artists"},
  %{"name": "BIS: 001-020", "rating": 6.8, "artist": "Various Artists"},
  %{"name": "A Sailor's Guide to Earth", "rating": 8.0, "artist": "Sturgill Simpson"},
  %{"name": "Blind Spot EP", "rating": 7.6, "artist": "Lush"},
  %{"name": "Become Alive", "rating": 6.7, "artist": "Dave Harrington Group"},
  %{"name": "Sleep Cycle", "rating": 7.6, "artist": "Deakin"},
  %{"name": "Love Letter for Fire", "rating": 7.5, "artist": "Sam Beam & Jesca Hoop"},
  %{"name": "Welcome the Worms ", "rating": 6.9, "artist": "Bleached"},
  %{"name": "Don't Look Down", "rating": 7.0, "artist": "Mr. Lif"},
  %{"name": "Missed Calls", "rating": 6.8, "artist": "Tunji Ige"},
  %{"name": "Singing Saw", "rating": 8.3, "artist": "Kevin Morby"},
  %{"name": "Sorrow - A Reimagining of Gorecki's 3rd Symphony", "rating": 7.8, "artist": "Colin Stetson"},
  %{"name": "Layers", "rating": 6.4, "artist": "Royce 5'9"},
  %{"name": "Crab Day", "rating": 8.1, "artist": "Cate Le Bon"},
  %{"name": "YYY EP", "rating": 6.0, "artist": "Tyler FriedmanSamuel Rohrer"},
  %{"name": "The Hope Six Demolition Project", "rating": 7.6, "artist": "PJ Harvey"},
  %{"name": "Plays the Music of Twin Peaks", "rating": 7.7, "artist": "Xiu Xiu"},
  %{"name": "Year of the Rabbit", "rating": 6.8, "artist": "Eskimeaux"},
  %{"name": "Fever Dream", "rating": 6.8, "artist": "Ben Watt"},
  %{"name": "Controlling Body", "rating": 8.1, "artist": "Peder Mannerfelt"},
  %{"name": "Kill 'Em All", "rating": 8.6, "artist": "Metallica"},
  %{"name": "Ride the Lightning", "rating": 10.0, "artist": "Metallica"},
  %{"name": "Everybody's Heart Is Broken Now", "rating": 7.8, "artist": "Niki and the Dove"},
  %{"name": "Nat Love", "rating": 8.0, "artist": "Kweku Collins"},
  %{"name": "Outer Heaven", "rating": 7.8, "artist": "Greys"},
  %{"name": "Commitment to Complications", "rating": 7.5, "artist": "Youth Code"},
  %{"name": "Gore", "rating": 7.8, "artist": "Deftones"},
  %{"name": "EARS", "rating": 8.0, "artist": "Kaitlyn Aurelia Smith"},
  %{"name": "Standards", "rating": 7.0, "artist": "Into It. Over It."},
  %{"name": "Ology", "rating": 7.5, "artist": "Gallant"},
  %{"name": "Psychic Lovers", "rating": 5.0, "artist": "Dinner"},
  %{"name": "Junk", "rating": 6.8, "artist": "M83"},
  %{"name": "Afterlife", "rating": 7.2, "artist": "DJ Rashad"},
  %{"name": "Painting of a Panic Attack", "rating": 6.0, "artist": "Frightened Rabbit"},
  %{"name": "More Issues Than Vogue", "rating": 7.9, "artist": "K. Michelle"},
  %{"name": "Azel", "rating": 7.8, "artist": "Bombino"},
  %{"name": "Human Performance", "rating": 8.4, "artist": "Parquet Courts"},
  %{"name": "Atomic", "rating": 7.1, "artist": "Mogwai"},
  %{"name": "Velvet Portraits", "rating": 7.8, "artist": "Terrace Martin"},
  %{"name": "Lost Time", "rating": 6.1, "artist": "Tacocat"},
  %{"name": "Love Streams", "rating": 8.2, "artist": "Tim Hecker"},
  %{"name": "Interview 2016", "rating": 7.0, "artist": "Death Grips"},
  %{"name": "City Sun Eater in the River of Light", "rating": 7.6, "artist": "Woods"},
  %{"name": "Twenty88", "rating": 6.5, "artist": "Twenty88"},
  %{"name": "Halfaxa", "rating": 7.8, "artist": "Grimes"},
  %{"name": "I AKA I", "rating": 7.5, "artist": "Ash Koosha"},
  %{"name": "Are You Serious", "rating": 7.2, "artist": "Andrew Bird"},
  %{"name": "It's the Big Joyous Celebration", "rating": 7.8, "artist": "Teen Suicide"},
  %{"name": "Old Locks and Irregular Verbs", "rating": 8.0, "artist": "Henry Threadgill Ensemble Double-Up"},
  %{"name": "Sept. 5th", "rating": 8.3, "artist": "dvsn"},
  %{"name": "Amen & Goodbye", "rating": 5.4, "artist": "Yeasayer"},
  %{"name": "Everything You've Come to Expect", "rating": 5.6, "artist": "The Last Shadow Puppets"},
  %{"name": "Pussy's Dead", "rating": 7.2, "artist": "Autolux"},
  %{"name": "Patch the Sky", "rating": 7.0, "artist": "Bob Mould"},
  %{"name": "The Follower", "rating": 7.9, "artist": "The Field"},
  %{"name": "Rojus", "rating": 7.8, "artist": "Leon Vynehall"},
  %{"name": "Super", "rating": 6.9, "artist": "Pet Shop Boys"},
  %{"name": "All Empires Fall", "rating": 7.8, "artist": "Tombs"},
  %{"name": "Silicon Tare EP", "rating": 5.9, "artist": "Com Truise"},
  %{"name": "Next Thing", "rating": 8.5, "artist": "Frankie Cosmos"},
  %{"name": "Eric Bachmann", "rating": 7.2, "artist": "Eric Bachmann"},
  %{"name": "The Rebellion Sessions", "rating": 7.1, "artist": "Black Milk & Nat Turner"},
  %{"name": "#N/A", "rating": 7.8, "artist": "Nisennenmondai"},
  %{"name": "Fleeting", "rating": 7.2, "artist": "Glenn Jones"},
  %{"name": "Slay-Z", "rating": 7.4, "artist": "Azealia Banks"},
  %{"name": "Changes", "rating": 7.1, "artist": "Charles Bradley"},
  %{"name": "IV", "rating": 7.5, "artist": "Black Mountain"},
  %{"name": "Three Men and a Baby", "rating": 7.0, "artist": "Mike and the Melvins"},
  %{"name": "Weezer (White Album)", "rating": 6.2, "artist": "Weezer"},
  %{"name": "Slime Season 3", "rating": 7.9, "artist": "Young Thug"},
  %{"name": "A Mineral Love", "rating": 6.8, "artist": "Bibio"},
  %{"name": "Empire Builder", "rating": 7.7, "artist": "Laura Gibson"},
  %{"name": "Living Life Golden", "rating": 6.7, "artist": "Elliphant"}
]

for album <- albums do
  artist = Repo.get_by(Artist, name: album.artist) ||
    Repo.insert!(%Artist{name: album.artist})

  Repo.get_by(Album, name: album.name) ||
  Repo.insert!(%Album{name: album.name, rating: album.rating, artist_id: artist.id})
end
